name: Build and deploy to Rsync

on:
  push:
    branches:
      - master #on push to the master branch do the jobs below
  workflow_dispatch:
  repository_dispatch:
    types:
      - build-and-deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: npm install and build
        run: |
          npm install
          npm run build

      - name: deploy with rsync
        run: |
          sudo apt-get install sshpass
          sshpass -p ${{ secrets.SSH_PASSWORD }} rsync --protocol=28 -avzh -e 'ssh -o StrictHostKeyChecking=no -p333' --delete  public/* lawebdee@estudiopablogallego.com:~/beta.estudiopablogallego.com >out.tmp
